name: Deploy to Google

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./build

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install libraries
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install # will run `yarn install` command
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build # will run `yarn build` command
      working-directory: ${{env.working-directory}}
    - name: install firebase
      run: npm i firebase-tools -g  
    - name: deploy
      run: firebase deploy --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LETMEASK_NOW }}
